add support for quay.io
silenceshell/docker_wrapper pull request #2
Opened 2019-07-30 11:45 UTC by chennqqi

Signed-off-by: chennqqi <chennqqi@qq.com>

2019-07-30 12:51 UTC, silenceshell requested changes
@chennqqi Thanks for your PR!
here are some review comments before merging:

2019-07-30 12:51 UTC, silenceshell commented on docker_wrapper.py
> +#
please remove the empty line begin comments

2019-07-30 12:51 UTC, silenceshell commented on docker_wrapper.py
> +#	 quay.io/xxx/yyy:zzz -> quay.azk8s.cn/xxx/yyy:zzz
please remove the tab ahead of this line

2019-07-30 12:51 UTC, silenceshell commented on docker_wrapper.py
> +	{
please use four blanks instead of tab

2019-07-30 12:51 UTC, silenceshell commented on docker_wrapper.py
> +			'replace': lambda x: x.replace('gcr.io', 'gcr.azk8s.cn'),
should be `quay.io` and `quay.azk8s.cn`

2019-07-30 12:51 UTC, silenceshell commented on docker_wrapper.py
> -    # image name like k8s.gcr.io/kube-apiserver:v1.14.1 or gcr.io/google_containers/kube-apiserver:v1.14.1
do not remove this comment, it is useful for quick reminding.

2019-07-30 12:51 UTC, silenceshell commented on docker_wrapper.py
> +			'replace': lambda x : 'dockerhub.azk8s.cn/library/' + x,
user may have set docker mirror and do not want to use own Azure mirror, so we should pull image directly.
I think this is not necessary.

2019-07-30 13:00 UTC, chennqqi commented
plz review again

2019-07-30 13:07 UTC, silenceshell commented
Ah...Please do not use [dos] style.

ref [here](https://help.github.com/cn/articles/configuring-git-to-handle-line-endings#global-settings-for-line-endings)

2019-07-31 01:35 UTC, chennqqi commented
to unix style

2019-07-31 02:00 UTC, chennqqi commented
change to unix style

2019-07-31 02:23 UTC, silenceshell commented
hi @chennqqi 

I have tested your code in my linux machine, and find out that the docker_wrapper.py is changed to `UTF-8 Unicode (with BOM) text executable`, and this will cause an error when exec:

```
./docker_wrapper.py pull gcr.io/google_containers/kube-apiserver:v1.14.1
./docker_wrapper.py: line 1: #!/usr/bin/python: No such file or directory
./docker_wrapper.py: line 4: import: command not found
./docker_wrapper.py: line 5: import: command not found
./docker_wrapper.py: line 11: converts: command not found
./docker_wrapper.py: line 14: syntax error near unexpected token `('
./docker_wrapper.py: line 14: `        'replace': lambda x: x.replace('gcr.io', 'gcr.azk8s.cn'),'
```

Please make sure the script could run on linux machine, for it is mainly used in this environment.

2019-07-31 02:30 UTC, chennqqi commented
convert dos to unix sytle shourd remove UTF-8 BOM

2019-07-31 03:09 UTC, silenceshell requested changes
hi please move this comment before line 8.

And squash your commit into one single commit. [Ref](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit)

2019-07-31 03:09 UTC, silenceshell commented on docker_wrapper.py
> +    	      # image name like k8s.gcr.io/kube-apiserver:v1.14.1 or gcr.io/google_containers/kube-apiserver:v1.14.1
please move this comment to line 8.

2019-09-16 08:37 UTC, merged

2019-09-16 08:38 UTC, silenceshell commented
@chennqqi thanks for your PR! 👍